name: Code analysis

on:
    push:
        branches:
            - develop
    pull_request:
        branches-ignore:
            - master
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    linters:
        runs-on: ubuntu-latest

        permissions:
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install Node.JS
              uses: actions/setup-node@v4

            - name: Cache modules
              uses: actions/cache@v4
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                      ${{ runner.os }}-npm-

            - name: Install modules
              run: npm ci

            - name: Run Type check
              run: npm run type-check

            - name: Run ESLint
              run: npm run lint-check

            - name: Run Prettier
              run: npm run prettier-check

            - name: Build project
              run: npm run build
